# Generated by Django 3.1.7 on 2021-04-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnumber', models.IntegerField()),
                ('sinput', models.TextField(null=True)),
                ('answer', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedCode',
            fields=[
                ('judgeid', models.IntegerField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('questionnumber', models.IntegerField()),
                ('username', models.TextField(null=True)),
                ('language', models.CharField(max_length=20)),
                ('code', models.TextField(null=True)),
                ('status', models.CharField(max_length=20)),
                ('casenum', models.IntegerField()),
                ('ac', models.IntegerField()),
                ('wa', models.IntegerField()),
                ('tle', models.IntegerField()),
                ('re', models.IntegerField()),
            ],
        ),
    ]
