# Generated by Django 3.0.7 on 2020-06-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owlapp', '0002_case_sinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedcode',
            name='ac',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submittedcode',
            name='casenum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submittedcode',
            name='re',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submittedcode',
            name='tle',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submittedcode',
            name='username',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='submittedcode',
            name='wa',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
