# Generated by Django 3.1.4 on 2020-12-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owlapp', '0004_submittedcode_judgeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='id',
        ),
        migrations.RemoveField(
            model_name='submittedcode',
            name='id',
        ),
        migrations.AlterField(
            model_name='case',
            name='questionnumber',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submittedcode',
            name='judgeid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
